baseURL = "https://helamanwarrior.github.io/infra-docs/"
languageCode = "en-US"
title = "Infra Docs"
theme = "reader"
canonifyURLs = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

